### ISSUE TITLE
0.1 Pick Design Tokens Sheet

### ISSUE THREAD

**Issue by jairpgjunior** [gstudioapp/gsystem#5]
**Given** I'm in the /home page

**And** the page is loaded

**And** the local storage is empty

**When I** pick which _**DesignTokensSheet**_  I want to use

**Then** all page elements should respond styles from picked _**DesignTokensSheet **_

**Comment by mpahenrique** [comment]
DS Tokens Reference: https://veritas.udacity.design/tokens/
